<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Failed suite [Surefire suite]" verbose="0">
  <test thread-count="5" name="Surefire test(failed)" verbose="0">
    <classes>
      <class name="extentia.tests.SubmitOrderTest">
        <methods>
          <include name="orderHistoryTest"/>
          <include name="launchApplication"/>
          <include name="submitOrder" invocation-numbers="0"/>
          <include name="tearDown"/>
        </methods>
      </class> <!-- extentia.tests.SubmitOrderTest -->
      <class name="extentia.tests.ErrorValidationsTest">
        <methods>
          <include name="launchApplication"/>
          <include name="productErrorValidation"/>
          <include name="tearDown"/>
          <include name="loginErrorValidation"/>
        </methods>
      </class> <!-- extentia.tests.ErrorValidationsTest -->
    </classes>
  </test> <!-- Surefire test(failed) -->
</suite> <!-- Failed suite [Surefire suite] -->
